### ISSUE TITLE
imgui wgpu tutorial

### ISSUE THREAD

**Issue by benmkw** [sotrh/learn-wgpu#110]
we could have a showcase for imgui-rs which describes how the crates involved relate

in short:
``` toml
wgpu = "^0.6.0"
winit = "^0.22.2" # opening windows and handling input
futures = "^0.3.5" # executing async functions using blocking executor
imgui = "^0.5.0"
imgui-winit-support = "^0.5.0" # connection of input (keys) to imgui
imgui-wgpu = "^0.11.0" # imgui backend for drawing using wgpu
```

something like this https://github.com/Yatekii/imgui-wgpu-rs/blob/master/examples/hello_world.rs
there is also imgui plotting now btw. https://github.com/4bb4/implot-rs

maybe also something how a wgpu backend for imgui works, it apparently gets lists of commands and then draws them
https://github.com/Yatekii/imgui-wgpu-rs/blob/fce781b5aaa9de40c98a1e5aa187d587c84b9c4b/src/lib.rs#L482-L497

As imgui is pretty popular for game UI I think this would be helpful and I found it to be really convenient to use so far :)
